#ifndef KGBASH_H
#define KGBASH_H

#define MAX_COMMANDS 12
#define COMMAND_ARRAY_LEN (MAX_COMMANDS + 1)
#define MAX_INPUT_LENGTH 512
#define INPUT_ARRAY_LEN (MAX_INPUT_LENGTH + 1)
#define QUIT_STRING "quit"

#endif // KGBASH_H